name: Publish

on:
  pull_request:
    branches: [main, hirte-*]
  workflow_dispatch:

jobs:

  ghrelease:
    name: Create GitHub release for BlueChi
    runs-on: ubuntu-latest
    container:
      image: quay.io/bluechi/build-base:latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: 'true'

      - name: Mark source directory as safe
        run: | 
          git config --global --add safe.directory $(pwd)
      
      - name: Build source rpm
        run: |
          ./build-scripts/build-srpm.sh
      
      - name: Get BlueChi version
        run: |
          echo "BLUECHI_VERSION=$(./build-scripts/version.sh)" >> $GITHUB_ENV

      - name: Create source zip and tarball
        run: |
          mkdir -p /tmp/bluechi-${{ env.BLUECHI_VERSION }}
          cp -r ./ /tmp/bluechi-${{ env.BLUECHI_VERSION }}/
          rm -rf /tmp/bluechi-${{ env.BLUECHI_VERSION }}/.git/
          mv /tmp/bluechi-${{ env.BLUECHI_VERSION }}/ ./ 

          zip -r bluechi-${{ env.BLUECHI_VERSION }}.zip bluechi-${{ env.BLUECHI_VERSION }}/
          tar czf bluechi-${{ env.BLUECHI_VERSION }}.tar.gz bluechi-${{ env.BLUECHI_VERSION }}/

          ls -la

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: bluechi-${{ env.BLUECHI_VERSION }}.tar.gz
          path: bluechi-${{ env.BLUECHI_VERSION }}.tar.gz
          if-no-files-found: error
